---
- name: Playbook to Install and Start Nginx
  hosts: Slave_Node
  become: true
  gather_facts: true  # Explicitly gather facts

  vars:
    ansible_python_interpreter: "/usr/bin/python3"  # Adjust the Python path as needed

  tasks:
    - name: Ensure Python 3 and pip are installed
      apt:
        name:
          - python3
          - python3-pip
        state: present
      when: ansible_distribution in ["Debian", "Ubuntu"]

    - name: Install six Python module if missing
      pip:
        name: six
        executable: "{{ ansible_python_interpreter }} -m pip"
        state: present
      when: ansible_distribution in ["Debian", "Ubuntu"]

    - name: Check Python six module
      command: "{{ ansible_python_interpreter }} -c 'import six'"
      register: six_check
      changed_when: false
      ignore_errors: true  # Allow task to continue even if it fails

    - name: Fail if six module is missing
      fail:
        msg: "The 'six' Python module is missing. Please install it on the remote host."
      when: six_check.rc != 0 and six_check.rc is defined

    - name: Update apt cache
      apt:
        update_cache: yes
      when: ansible_distribution in ["Debian", "Ubuntu"]

    - name: Install Nginx
      apt:
        pkg:
          - nginx
        state: present
      when: ansible_distribution in ["Debian", "Ubuntu"]

    - name: Ensure Nginx is running
      service:
        name: nginx
        state: started
      when: ansible_distribution in ["Debian", "Ubuntu"]

    - name: Check Nginx Status
      service:
        name: nginx
      register: nginx_status
      changed_when: false

    - name: Display Nginx Status
      debug:
        var: nginx_status.status