---
- name: Installation et démarrage de Nginx
  hosts: Slave_Node
  become: true  # Exécuter en mode root
  tasks:
    - name: Mise à jour du cache APT
      apt:
        update_cache: yes

    - name: Installation de Nginx
      apt:
        name: nginx
        state: present

    - name: S'assurer que Nginx est activé et en cours d'exécution
      service:
        name: nginx
        state: started
        enabled: yes
